### PR TITLE
Added maven artifact support

### PR DESCRIPTION
**Pull request by pvanassen**
Added maven publish support to allow us legacy maven users to easily allow using the api.

### CODE REVIEW

**Comment by langerhans** [comment]
Is this for the sources jar and if so will it now be built twice? Cause I added the sources export just yesterday above your change.

**Comment by pvanassen** [comment]
No, this is to publish the compiled and sources jar together with the pom.xml into your local .m2 or a remote maven repository. It should not do things twice

**Comment by langerhans** [comment]
This already happens when you run `./gradlew install`. Don't think that change is required for this.

**Comment by pvanassen** [comment]
Alright, in that case you can close it. Sorry for the inconvenience.

**Pull request closed without merging**
