### PR TITLE
Add an interface to PokemonIdValue from CatchablePokemon

### PR DESCRIPTION
**Pull request by AbandonedCart**
This allows referencing the individual class getPokemonIdValue directly from the CatchablePokemon object

### CODE REVIEW

**Comment by FabianTerhorst** [comment]
Is the pokemon id value the same as CatchablePokemon cp; cp.getPokemonId().getNumber() ?

**Comment by FabianTerhorst** [comment]
the proto java file is wrapping the id from getPokemonIdValue to create the enum object for getPokemonId()

**Comment by AbandonedCart** [comment]
MapPokemon pokemon.getPokemonIdValue()
WildPokemon:  pokemon.getPokemonData().getPokemonIdValue()
FortLureInfo: lureInfo.getActivePokemonIdValue()

Whether or not it is provided through an alternate means, this makes it uniform with the rest of the API, which offer both values individually

**Comment by FabianTerhorst** [comment]
We have never wrapped the value int from the proto file to the wrappers before.

**Comment by AbandonedCart** [comment]
Are you trying to say the type is wrong or is there some other issue other? If you meant the type was wrong, that can easily be changed. It sounds like you were against the entire idea, though, which honestly makes no sense.

**Comment by FabianTerhorst** [comment]
I mean you are the one that told us that this project has to much methods and now you want to add a duplicate way to access a value.

**Comment by AbandonedCart** [comment]
So there isn't an issue with the PR? Because the type is correct.

Int

**Comment by FabianTerhorst** [comment]
I never told that the type is incorrect. I just said that this is a duplicate way to access the value.

**Comment by AbandonedCart** [comment]
`We have never wrapped the value int from the proto file to the wrappers before` was a little confusing then, since all of them are int values.

The merit of `getPokemonIdValue` is that when used in an application that has it's own collection of references, for example images, you avoid the overhead of getting the wrapped object and then unwrapping it again to make an already expensive call to get the image for that pokedex value.

If the choice is between one getter in an API that already forces MultiDex or the overhead of having to make up to 151 calls to unwrap a wrapped value only to avoid that one method, it's a no-brainer.

**Pull request merged**
