### PR TITLE
add lure pokemon to CatchablePokemon

### PR DESCRIPTION
**Pull request by jabbink**

### CODE REVIEW

**Comment by jabbink** [comment]
Untested, don't have a lure around me.

**Comment by ConstantinCiot** [comment]
WildPokemons are not the pokemons spawned by lure.
NearbyPokemon is what we need .. those are the lured pokemons

**Comment by mjmjelde** [comment]
NearbyPokemon are not lured.  Those are the ones that appear on the radar

**Comment by jabbink** [comment]
Multiple people confirmed me that lured pokemon are the ones that this code adds.

**Pull request merged**
