### PR TITLE
Update pogoprotos

### PR DESCRIPTION
**Pull request by Furtif**

### CODE REVIEW

**Comment by Gegy** [comment]
Could you make this send too?

**Comment by Furtif** [comment]
???

**Comment by Furtif** [comment]
What's ? Is an update of pogoprotos nothing more

**Comment by Furtif** [comment]
https://github.com/Grover-c13/PokeGOAPI-Java/issues/288 is false it is the 288 aleonlucid

**Comment by LoungeKatt** [comment]
It probably looked misleading because this is done through the module

https://github.com/Grover-c13/PokeGOAPI-Java/blob/Development/.gitmodules

**Comment by Furtif** [comment]
yes https://github.com/AeonLucid/POGOProtos/tree/7c518c1202420fd769c08eea45a47629808af27c
to https://github.com/AeonLucid/POGOProtos

**Comment by Furtif** [comment]
https://github.com/Grover-c13/PokeGOAPI-Java/tree/Development/library/src/resources

**Comment by AbandonedCart** [comment]
I removed the unnecessary step-by-step module path comments. Posting a PR that says anything besides "Update Protos" or some variation of that will look like you are proposing actual changes to the library. If the Proto changes the library code, updated library code is also recommended, though.

**Comment by Gegy** [comment]
Should the hashing endpoint not also be changed?

**Comment by Furtif** [comment]
Is v137_1 eggy as made annoncement

**Pull request merged**
