### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by EdbertChan**
**Changes made:**
Added step-by-step on how to add the project to Android Studio.

### CODE REVIEW

**Comment by FabianTerhorst** [comment]
Are you sure the path is working with the latest commit?

**Comment by FabianTerhorst** [comment]
/PokeGOAPI-Java/library

**Comment by EdbertChan** [comment]
It works fine with mine. Is there something wrong when you try it with yours?

**Comment by AbandonedCart** [comment]
@EdbertChan The PR submitted by @FabianTerhorst for multi-module was recently merged. The README was only partially updated to document them, but the resulting jar is named `library-all.jar` and has moved to a `library` subfolder. The first commit of https://github.com/Grover-c13/PokeGOAPI-Java/pull/430 has the additional changes to the README. The full commit is https://github.com/Grover-c13/PokeGOAPI-Java/commit/cca2a1cf0bdc2ba18d6863f91edd156d463273cc

**Comment by EdbertChan** [comment]
Ok I'll wait for the merge to finish and revise my editing.

**Comment by AbandonedCart** [comment]
@EdbertChan It's finished. The PR I referred you to was just for some additional README changes.

**Comment by EdbertChan** [comment]
Ok will do tonight or tomorrow.

**Comment by FabianTerhorst** [comment]
Im not sure if this is working. Even when it would you should better add the library module then instead of the project.

**Comment by EdbertChan** [comment]
I was getting a lot of problems trying to add it as a module and this is meant to be a work around.

**Comment by AbandonedCart** [comment]
@EdbertChan in Android Studio, it works to simply add the import code to gradle or use one of the examples in the readme to include a built version locally. (Edit: Revised for updated README)
Adding the entire project is excessive, though.

**Comment by Grover-c13** [comment]
Is this still up to date?

**Comment by FabianTerhorst** [comment]
Im not sure, but i think the module name changed from PokeGOAPI to PokeGOAPI-library or to library.

**Comment by Grover-c13** [comment]
Ill close for now.

**Pull request closed without merging**
