### PR TITLE
Inventories and Settings not loaded at initialization.

### PR DESCRIPTION
**Pull request by gdespres**
**Fixed issue:**
 #727

**Changes made:**
index of Inventories and Settings request are wrong

### CODE REVIEW

**Comment by FabianTerhorst** [comment]
@iGio90 review please

**Comment by FabianTerhorst** [comment]
why this is fixing #727? The inventory api is providing the stats. So when you want now stats you have to update the inventory. https://github.com/Grover-c13/PokeGOAPI-Java/blob/Development/library/src/main/java/com/pokegoapi/api/inventory/Inventories.java#L155

**Comment by iGio90** [comment]
@FabianTerhorst yeah, the index are changed when I added the check challenge at the first position. However, my rework on PR will get rid of all of this things and parse each response from the common request class

**Comment by iGio90** [comment]
Maybe it won't fox #727 but the fix is right in any case

**Comment by FabianTerhorst** [comment]
ok then, but #727 isn´t an issue.

**Comment by gdespres** [comment]
Maybe it won't fix #727, but I think there is a link with the issue because Inventories was not updated at login().

call manualy go.getInventories().updateInventories() resolve it.

**Comment by gdespres** [comment]
now inventories (and settings) are updated at login() and manualy call go.getInventories().updateInventories() is not needed

**Comment by FabianTerhorst** [comment]
its needed when you catched a pokemon.

**Comment by FabianTerhorst** [comment]
So that the xp is changing.

**Pull request merged**
