### PR TITLE
Replace gson with moshi to improve performance and reduce library size

### PR DESCRIPTION
**Pull request by FabianTerhorst**
Moshi is depending on okio as well as okhttp. More informations: https://github.com/square/moshi

### CODE REVIEW

**Comment by FabianTerhorst** [comment]
sorry, wrong branch.

**Comment by Grover-c13** [comment]
this was the right branch, we are switching to a stable master, and a development branch :P

**Comment by FabianTerhorst** [comment]
ah ok, because travis doesn´t started building.

**Comment by Grover-c13** [comment]
True will need to fix that.

**Comment by FabianTerhorst** [comment]
I have to add a commit i think to trigger travis again?

**Comment by Grover-c13** [comment]
yeah to inc the latest config

**Pull request merged**
