### PR TITLE
switch to protobuf 3 and use generated sources instead of compiled sources in the repo

### PR DESCRIPTION
**Pull request by jabbink**
With this, there is no need to manually regenerate the `java` files for new protobufs.

I removed all `optional`/`required` things, because in Protobuf 3, everything is optional.

Also reindented to make it consistent across all proto files,

Also added specified java version `1.8` in the `pom.xml` because otherwise IntelliJ kept reimporting the `pom.xml` and reset the compiler level to `1.5`.

### CODE REVIEW

**Comment by jabbink** [comment]
Warning, not sure if this breaks the API, or the RPC is offline/broken once again, because right now, all I get are `com.google.protobuf.InvalidProtocolBufferException: Protocol message had invalid UTF-8.` errors (and sometimes the failed to respond error).

**Comment by Grover-c13** [comment]
Okay will hold off for now and check the servers/

**Comment by Grover-c13** [comment]
"Also added specified java version 1.8 in the pom.xml because otherwise IntelliJ kept reimporting the pom.xml and reset the compiler level to 1.5."

We may be looking at going for java 1.6 for android compatibility in future, just heads up.

**Comment by jabbink** [comment]
switching back to `master`: `com.google.protobuf.InvalidProtocolBufferException: Message missing required fields: items[3].item.PlayerStats.PrevLevelExp, items[3].item.PlayerStats.KmWalked, items[3].item.PlayerStats.NumEvolutions, items[3].item.PlayerStats.PokeStopVisits, items[3].item.PlayerStats.NumberOfPokeballThrown, items[3].item.PlayerStats.NumEggsHatched, items[3].item.PlayerStats.BigMagikarpCaught, items[3].item.PlayerStats.NumBattleAttackWon, items[3].item.PlayerStats.NumBattleAttackTotal, items[3].item.PlayerStats.NumBattleDefendedWon, items[3].item.PlayerStats.NumBattleTrainingWon, items[3].item.PlayerStats.NumBattleTrainingTotal, items[3].item.PlayerStats.PrestigeRaisedTotal, items[3].item.PlayerStats.PrestigeDroppedTotal, items[3].item.PlayerStats.NumPokemonDeployed, items[3].item.PlayerStats.SmallRattataCaught
`

So either the niantic server is broken, my PTC test account is banned, or something else is horribly wrong (and yes, I know that many fields marked as "required" are not actually required, but right now it isn't even returning my username, account creation date, etc)

Also: I _had_ to set that 1.8 compiler level, because someone added https://github.com/Grover-c13/PokeGOAPI-Java/blob/master/src/com/pokegoapi/api/inventory/PokeBank.java#L29

**Comment by Grover-c13** [comment]
Yeah we will be taking lombok back out soon, https://github.com/Aphoh/PokeGOAPI-Java/

**Comment by jabbink** [comment]
Ah, nice, Gradle, was already thinking about making a PR that kills Maven :joy:

I'll wait for that merge then, and recheck if this works.

**Comment by Grover-c13** [comment]
Does it return any proto when logging in?

**Comment by jabbink** [comment]
No idea. Not in a position to test that right now (no wireshark or anything installed here).

I assume not, as the protobuf 3 implementation complains about not receiving proper UTF-8 data.

**Comment by jabbink** [comment]
Solved, my bad.

https://github.com/Grover-c13/PokeGOAPI-Java/issues/11#issuecomment-233275665

**Comment by jabbink** [comment]
(I didn't commit it yet :hushed:, can you please fix this line https://github.com/Grover-c13/PokeGOAPI-Java/blob/master/src/com/pokegoapi/requests/ProfileRequest.java#L23 ?;
when that's a `GET_PROFILE` the API works again.)

**Pull request merged**
