### PR TITLE
use safe implementation of XXHashFactory to make API workable on Android

### PR DESCRIPTION
**Pull request by mgorski-mg**

### CODE REVIEW

**Comment by FabianTerhorst** [comment]
We could also use a check to determinate if the running platform is android, like okhttp, but maybe using the same for all platforms should be ok.

**Comment by broach** [comment]
Tested on Android and is working perfectly 👍

**Comment by AbandonedCart** [comment]
Checking for platform dependency is only a good option if the performance hit is significant. If this doesn't make a big difference and works, then it makes more sense.

**Comment by broach** [comment]
Given the throttling on requests being so massive (in relative terms) I sincerely doubt a few microseconds is going to matter much when calculating the hash.

**Comment by mgorski-mg** [comment]
I agree with you. What do you think @FabianTerhorst?

**Comment by FabianTerhorst** [comment]
Is the speed worth the platform check?

**Comment by mgorski-mg** [comment]
I don't think so, as @broach said few milliseconds is nothing comparing to api throttle.
But if you want we could check what is the time difference. But I can't do it right now.

**Comment by jabbink** [comment]
I assume the `safeInstance` doesn't use the native implementations at all? Then maybe to decrease the size of this API only include the version without the JNI dep.

**Comment by mgorski-mg** [comment]
@jabbink Do you think about changing the library to different which contains only safe java implementation? Or to shrink this one?

**Comment by AbandonedCart** [comment]
Honestly, there is no real need for the entire lz4 library. xxhash is significantly smaller on its own.

**Comment by vmarchaud** [comment]
@mgorski-zlatan Try implementing another lib or including only the safe instance (lz4 is under Apache2, we should be able to include it under ours by keeping the license header).

**Comment by jabbink** [comment]
I then suggest stripping out the entire lz4 dep and include a Java impl of xxhash only.

I think it's weird it doesn't work on android though, as https://github.com/jpountz/lz4-java/blob/master/src/java/net/jpountz/xxhash/XXHashFactory.java#L128 wraps everything in try/catch, on fail loads the `fastestJavaInstance`, which in case of failure loads `safeInstance`.

**Comment by FabianTerhorst** [comment]
@mgorski-zlatan you want to do what @jabbink is suggestion or should someone else doing it?

**Comment by mgorski-mg** [comment]
Ok, I'll implement it.
@jabbink it's not working because android Unsafe class hasn't got getByte() method, so it can't be checked while initializing.

**Comment by FabianTerhorst** [comment]
@mgorski-zlatan i would suggest you to create it as an different module.

**Comment by jabbink** [comment]
(also make sure the picked impl actually works, many xxhash64 impls return garbage from what I've seen over the past days, xxhash32 seems to be implemented consistently over multiple platforms/languages)

**Comment by kyr0** [comment]
Yeah, well I tried this and I'm getting:
java.lang.ClassNotFoundException: Didn't find class "net.jpountz.xxhash.XXHash32JavaSafe" on path

Any ideas? :)

My gradle includes dependency:

```
compile 'net.jpountz.lz4:lz4:1.3.0'
```

**Comment by kyr0** [comment]
@mgorski-zlatan Just tell me if you want me to test/do anything; we are in the same boat :)

**Comment by mgorski-mg** [comment]
If you want to help feel free. I didn't finish if yet, because I came from the work few minutes ago.

**Comment by mgorski-mg** [comment]
@kyr0 If you have time today please feel free to change xxhash implementation, because I'll probably have no time today

**Comment by kyr0** [comment]
Well, I figured out that the error disappeared as soon as I changed from:

```
buildTypes {
    debug {
        minifyEnabled true
        proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
    }
    release {
        minifyEnabled true
        proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
    }
}
```

To:

```
buildTypes {
    debug {
        minifyEnabled false
        proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
    }
    release {
        minifyEnabled false
        proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
    }
}
```

So disabling the minification process and thus proguard makes the jar's being available in the  resulting APK. 

**So seems like this isn't a library issue. It's a project-local Proguard rules issue (?)**

**Comment by FabianTerhorst** [comment]
you have to add a proguard rule to keep net.jpountz.xxhash.XXHash32JavaSafe

**Comment by broach** [comment]
Mine was already set to **minifyEnabled false** which is why I didn't run into further probs, sorry.

**Comment by FabianTerhorst** [comment]
proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro' is useless when you disable it with false

**Comment by FabianTerhorst** [comment]
btw this is definitely not a mistake from proguard, because proguard can´t know when an application needs an class and is only accessing this class with reflection.

**Comment by kyr0** [comment]
> btw this is definitely not a mistake from proguard, because proguard can´t know when an application needs an class and is only accessing this class with reflection.

What I wanted to say: Local project configuration issue with proguard; for the time being I disabled it completely by setting minifyEnabled to false. (Later: Rules have to be added; so: Local proguard config issue) 

What was understood by you: proguard has an issue. 

Sorry, I never wanted to say that proguard has an issue.

**Comment by FabianTerhorst** [comment]
`-keep public class net.jpountz.xxhash.XXHash32JavaSafe`  inside your proguard file should fit it.
Edit better: `-keep public class net.jpountz.xxhash.*`

**Comment by cesco89** [comment]
@FabianTerhorst Thanks a lot!!!!
You are my hero! :D

**Comment by cesco89** [comment]
Ok so, tried adding that flag to proguard and doesn't work.
On some devices keeps crashing (ZenFones and some other devices with android 5.x).
Also, i don't know if multidex is another crash cause with the updated library (4.0 up to date with latest commits)
i had to revert to an older version of the library to kill the 90% of the crashes

**Comment by AbandonedCart** [comment]
```
-keepattributes *Annotation*
-keepattributes Signature
-keepattributes InnerClasses

-keep class org.apache.http.** { *; }
-keep class com.pokegoapi.** { *; }
-keep class POGOProtos.** { *; }
-keep class okhttp3.** { *; }
-keep class okio.** { *; }
-keep class com.google.protobuf.** { *; }
-keep class rx.** { *; }
-keep class net.jpountz.** { *; }

-dontwarn org.apache.http.**
-dontwarn com.pokegoapi.**
-dontwarn POGOProtos.**
-dontwarn okhttp3.**
-dontwarn okio.**
-dontwarn com.google.protobuf.**
-dontwarn rx.**
-dontwarn net.jpountz.**

-dontnote org.apache.http.**
-dontnote com.pokegoapi.**
-dontnote POGOProtos.**
-dontnote okhttp3.**
-dontnote okio.**
-dontnote com.google.protobuf.**
-dontnote rx.**
-dontnote net.jpountz.**

-keepattributes Exceptions,SourceFile,LineNumberTable
```

This is a sample ProGuard file from the application importing the library.
The last line is only if you want to have your native stacktrace deciphered.
(You can also use proguard tools to decipher a minified / obfuscated trace)

**Comment by AbandonedCart** [comment]
Is it safe to assume we are all using this anyway?

**Pull request merged**
