### PR TITLE
add binary plugin to library module

### PR DESCRIPTION
**Pull request by FabianTerhorst**
use ./gradlew :library:bintrayUpload to test script (remove org.gradle.configureondemand=true in grade properties to resolve jar generation error)

Todo: javadoc isnt submitted.

### CODE REVIEW

**Comment by FabianTerhorst** [comment]
@Grover-c13 you have to create a account at bintray.com . Then you have to change your gradle properties and add there the user and apiKey, but don´t commit the properites. After the first upload script you have to confirm the project on your account and add a request for publish to jcenter.

**Comment by AbandonedCart** [comment]
What is the benefit of this over, for example, Github releases (which are already supported and require no additional imports to be added)?

**Comment by s7092910** [comment]
@LoungeKatt you just do a gradle build and it puts it on bintray which is jcenter. So anyone wanting to add it to their gradle build, they can just do 'compile 'project-blah:version-blah'. And depending on your IDE, it will notify you if there is a new version out. A lot easier on the user to use. Jcenter is sort of the new standard when it comes to Java libraries or even Android libraries.

**Comment by FabianTerhorst** [comment]
It's much Cleaner to use then jitpack. The jcenter releases will never be end unresolved dependencies and you know exactly what is released.

**Comment by AbandonedCart** [comment]
@s7092910 Not sure I would call one less line a whole lot easier, but thanks for the explanation anyway. With how often the repo updates, I assume this is more of a long term goal.

**Comment by FabianTerhorst** [comment]
Normally this is the first think thats happening before a library is getting released.

**Comment by FabianTerhorst** [comment]
he is failing, because local properties doesn´t exists in github and shouldn´t exists.

**Comment by Grover-c13** [comment]
wont it fail for all builds in future then?

**Comment by FabianTerhorst** [comment]
i will fix it. Maybe submit a empty local.properties file?

**Comment by FabianTerhorst** [comment]
this commit could fix it.

**Comment by FabianTerhorst** [comment]
@Grover-c13 travis is fixed

**Comment by FabianTerhorst** [comment]
you created an account?

**Comment by FabianTerhorst** [comment]
i have tested the upload https://bintray.com/fabianterhorst/maven/PokeGOAPI

**Comment by Grover-c13** [comment]
yeah setting it up now, please feel free to join slack to offer me technical support :P

**Comment by LoungeKatt** [comment]
@FabianTerhorst When you update the README, please make sure to update the **ENTIRE** relevant section, not just the single line of code that changed. You left a whole section on using jitpack, including the link to jitpack, wrapping this new method.

**Pull request merged**
