### PR TITLE
Staticauth

### PR DESCRIPTION
**Pull request by pvanassen**
**Fixed issue:** https://github.com/Grover-c13/PokeGOAPI-Java/issues/214

### CODE REVIEW

**Comment by FabianTerhorst** [comment]
👍

**Comment by Aphoh** [comment]
@pvanassen This is good but REFRESH_TOKEN_MAP is a confusing name. You don't need the type in the name. Something like OAUTH_REFRESH_TOKENS would be much easier to understand.

**Comment by pvanassen** [comment]
I don't see why, the name is clear. Feel free to change it after merge.

**Comment by FabianTerhorst** [comment]
I would stay with REFRESH_TOKENS.

**Comment by pvanassen** [comment]
This bug is also fixed by https://github.com/Grover-c13/PokeGOAPI-Java/pull/234

**Pull request closed without merging**
