### PR TITLE
Changed CredentialProviders to allow easier extending of existing CredentialProviders

### PR DESCRIPTION
**Pull request by s7092910**
**Changes made:**
- Changed private fields in GoogleUserCredentialProvider and PTCCredentialProvider to protected so they are visible in child classes.
- Allows easier modifications of these classes outside of the API.

### CODE REVIEW

**Comment by Jari27** [comment]
Right now there are only PTC and Google logins. I don't see that changing in the near feature. If it doesn't, less visibility is better, imho.

Thoughts?

**Comment by vmarchaud** [comment]
If you want to make change to a provider, why not implementing your own since the interface is public ? It should be simpler for you i think.

**Comment by s7092910** [comment]
@vmarchaud that is what I told the rest of my team, but they said it would be better to extend the already existing CredentialProvider. And they wanted me to make this PR. But I would say this would be a nice idea, for instance I know people have been asking for a method in the PTCCredentialProvider to take in a TokenId. This in theory would allow them to do that along with if they want to change a bit of how the internals of the Provider works, without having to rewrite everything.

**Comment by vmarchaud** [comment]
@s7092910 
I agree that the lib is actually may be too high level for people that know who the networking is done, thats why i'm making [another lib](https://github.com/vmarchaud/pogoapi) (that maybe will get introduced into the java implementation) that doesnt force any implementation of auth, just provide interface to do it.
In regard of your PR, wait for @Grover-c13 for this PR, i personally prefer that your team make their provider has they want to over allow the modification of our provider.

**Comment by rajulbhatnagar** [comment]
If you want to implement your provider to suit your needs you can do so by implementing the interface however I do feel that making those fields protected is reasonable enough. I dont see any downside to it. @vmarchaud Do you see any downsides to this?

**Comment by Grover-c13** [comment]
@s7092910 are you on the PKRE slack?

**Comment by s7092910** [comment]
@Grover-c13 No I'm not, do you want me to join?

**Comment by Grover-c13** [comment]
nothing major just wanted to discuss something relating to the login providers and the API :P

**Pull request merged**
