### PR TITLE
Fix powerup and evolution cp calculation

### PR DESCRIPTION
**Pull request by mgorski-mg**

### CODE REVIEW

**Comment by Grover-c13** [comment]
Thankyou, could you rebase when you get a chance and will merge.

**Comment by mgorski-mg** [comment]
@Grover-c13 done

**Comment by mgorski-mg** [comment]
@Grover-c13 you can merge this PR

**Comment by FabianTerhorst** [comment]
Checkstyle runs without problems?

**Comment by FabianTerhorst** [comment]
Why are the changes from the last pr inside yours as well?

**Comment by FabianTerhorst** [comment]
Maybe try to recreate the pr

**Comment by mgorski-mg** [comment]
@FabianTerhorst yup,checkstyle runs without any problems.
There are only my changes in this PR. What do you mean?

**Comment by FabianTerhorst** [comment]
Nvm this was just the merge commit.

**Comment by mgorski-mg** [comment]
No problem :)

**Pull request merged**
