### PR TITLE
[WIP][Part3][Requres Part2 + Part 2.1]Rework login flow

### PR DESCRIPTION
**Pull request by FabianTerhorst**

### CODE REVIEW

**Comment by FabianTerhorst** [comment]
We should thing about removing or deprecating the option to set a http client to the providers inside this pr.

**Comment by LoungeKatt** [comment]
Is this complete in its current state? Disregarding additional plans for how to improve it, can this be deployed for the end user to begin reworking the flow in their code?

**Comment by AbandonedCart** [comment]
This still needs a constructor that allows setting just the http client (since the only method to do that is by filling in every other value) unless that is completely removed and / or a check before declaring a new client in each of the other constructors otherwise it still declares a new one each time when not calling the one with all values.

**Comment by FabianTerhorst** [comment]
We decided to pass the http client with the .login(provider) method.

**Pull request closed without merging**
