### PR TITLE
Catch pokemon automatically poke ball

### PR DESCRIPTION
**Pull request by Cyperghost**
This function choose automatically the right ball to catch a pokemon

### CODE REVIEW

**Comment by FabianTerhorst** [comment]
you run checkstyle?

**Comment by Cyperghost** [comment]
Yes, and no errors ;)

**Comment by pvanassen** [comment]
What I've seen is the probability levels overall being very low. Have you tested this code in the wild? It might in most cases select the best pokeball you have. Personally I use a cutoff of 35% because 50% was too high, let alone 75%.

**Comment by Cyperghost** [comment]
I often test it with 30% than the pokemons flee.
I think i can changed it to 50%, but less i think it´s that flee,too.

**Comment by pvanassen** [comment]
It would be interesting to gather some data. I don't comment on this PR because you need to change it btw. More as a point of debate.

**Comment by john086** [comment]
Where is this method ? Is an update on catch pokemon method?

**Pull request merged**
