### PR TITLE
getItemsCount function

### PR DESCRIPTION
**Pull request by ramarro123**
**Changes made:**
added a method to get the used spaces on bag.
useful to trigger actions based on remaining space on the bag

### CODE REVIEW

**Comment by Jari27** [comment]
Can you document it? Otherwise someone else will have to do it some day.

Also, I think checkStyleMain doesn't allow one character variables. Maybe change it to `Item item`?

**Comment by ramarro123** [comment]
here we go

**Comment by williamho** [comment]
isn't this the same as `items.size()`?

**Comment by Deagler** [comment]
No, It isn't the same. That isn't the way the ItemBag works.

**Comment by williamho** [comment]
oh sorry, I misread

**Pull request merged**
