### PR TITLE
Modified Pokemon.java

### PR DESCRIPTION
**Pull request by gionata-bisciari**
**Changes made:**
- Fixed Pokemon.canEvolve():boolean, now checks if the pokemon reached the maximum evolution form;
- Added Pokemon.canPowerUp(considerMaxCPLimitForPlayerLevel:boolean):boolean so now passing true it checks if the pokemon already reached its current maximum cp for player level

### CODE REVIEW

**Comment by gionata-bisciari** [comment]
@LoungeKatt is this ok?

**Comment by AbandonedCart** [comment]
Perfect. Thanks!

**Comment by gionata-bisciari** [comment]
Thanks to you and sorry again

**Comment by AbandonedCart** [comment]
Just some minor checkstyle stuff and it should be good to go.
canPowerUp needs spacing around the parenthesis and brackets, plus the else should be on the same line as the closing if bracket.

**Comment by gionata-bisciari** [comment]
I'm going to check

**Pull request closed without merging**
