### PR TITLE
Add Native Walking API

### PR DESCRIPTION
**Pull request by mackenzieg**
Just wanted to add some native walking to the APi, should add a little bit of randomness to to the walking as to not trigger the server detecting our perfect locations.

### CODE REVIEW

**Comment by FabianTerhorst** [comment]
You can use rxjava timer functions to make it fit better into the project.

**Comment by AbandonedCart** [comment]
Isn't this more for the individual client?
I know in my case, with a mock location client included, this is overhead.

It would be great for the sample project, though.

**Comment by FabianTerhorst** [comment]
you can create a sample with a walking logic.

**Comment by Grover-c13** [comment]
this is outside the scope of the API sorry.

**Pull request closed without merging**
