### PR TITLE
Add method for request Tutorial complete.

### PR DESCRIPTION
**Pull request by iGio90**
Some recent serverside changes now force the new accounts to accept tos before making requests. 

If any other can confirm, is working good for me!

### CODE REVIEW

**Comment by broach** [comment]
Is this just fire-and-forget? When does it need to be called? What happens if the account has already accepted the TOS? 

Is there a server response sent when you try to use the API / log in telling you that you need to accept the TOS that this could be automatically sent as the reply?

**Comment by AbandonedCart** [comment]
Depending if the server actually verifies, logs, or discards an overlapping attempt to accept will determine if this statement is relevant, but it appears be a fire and forget as part of the first login process (per account) by the user.
There should be a value provided by the server that it needs acceptance, so it would likely be possible to query the server if it required, but then you run into facing rate limits and such for something that is most likely going to be discarded by the endpoint if it is unnecessary.

**Comment by broach** [comment]
I created a new PTC account and attempted to use this. No worky. 

The account authenticates and I get back the PtcCredentialProvider.  I instantiate a new PokemonGo and then call this new skipTos(). Subsequent API calls return empty; the account isn't past the TOS thing.

**Comment by iGio90** [comment]
I just get awake and im gonna focus on it again! Im from phone now but i toke the idea from a python script linked in the issues. I think i replicated it right, but give it look please.

Anyway, I dont really know how they are doing it on server side because at the very first, i had valid response, then nothing as you said.

Edit: here is the script
https://github.com/keyphact/pgoapi/blob/691aff2543c39ba929e4aa0e325dc43d24cb24df/scripts/accept-tos.py

The request send tutorials_completed with value 0, maybe we have to use another value? ref:

https://github.com/AeonLucid/POGOProtos/blob/master/src/POGOProtos/Enums/TutorialState.proto

**Comment by iGio90** [comment]
Anyway, I dont really know how they are doing it on server side because at the very first, i had valid response, then nothing as you said.

**Comment by iGio90** [comment]
Update: The python script that i linked seems not working either. 
- It's not related to ToS. You can send valid request even without agree to tos.
- It will works once you log in with the official client, so you put the tutorial status to legal screen.

Repliceation: Create a new account either ptc/google. Run the call to set the tutorial into legal screen either with my impl or with the python script. Empty responses.
After the login with the official client it will fill the responses, even the one to put the tutorial into legal screen. Going for further investigation, is anyone having a look into?

Im going to MITM and check what happens at the first login

**Comment by AbandonedCart** [comment]
It might be that by accepting the TOS, you are kicking into the tutorial and don't have a configuration to either eject or go through it. I dunno coming from an existing account, but it seems like before the bot would sidestep the entire process, but now it may be a callback (ie. if tos then avatar).

I could also be just rambling because I haven't looked at how python is actually doing it.

**Comment by broach** [comment]
Yeah, I think to automate this is going to require looking at a MITM sequence for a new account and seeing what the game is doing.

**Comment by iGio90** [comment]
It is! Im going ti retry once im back home! Today i tried both with xposed module and modified apk but didnt get Charles to work! If you are on it, just check what it goes out on the very first login of a fresh account! It happens before tos and before the call to set the status to login screen! (Almost sure)

**Comment by iGio90** [comment]
Sorry i meant legal screen, cant edit comment with phone

**Comment by iGio90** [comment]
Between login and ToS 

<-] Request for GetPlayer  { app_version: '0.31.0', '$unknownFields': [] }

[<-] Request for DownloadRemoteConfigVersion  { platform: 'ANDROID', app_version: 3100, '$unknownFields': [] }

[<-] Request for GetHatchedEggs  {}

[<-] Request for GetInventory  {}

[<-] Request for CheckAwardedBadges  {}

[<-] Request for DownloadSettings  {}

[<-] Request for DownloadItemTemplates  {}

[<-] Request for GetHatchedEggs  {}

[<-] Request for GetInventory  { last_timestamp_ms: '1470696953513', '$unknownFields': [] }

[<-] Request for CheckAwardedBadges  {}

[<-] Request for DownloadSettings  { hash: '6e9c84cbb761ec75078bb8f787559580b23a302b',
  '$unknownFields': [] }

**Comment by iGio90** [comment]
@broach well.. i think Im done. It want this --> GetPlayer. Verified on 2 fresh accounts, it reply to the move to legal screen.

**Comment by jay8ee** [comment]
Are you still working on this? Be nice to get this into dev

**Comment by iGio90** [comment]
Of course! I finished it but im unable to remove this PR. Check my other PR (WIP tutorial state)

**Comment by jay8ee** [comment]
Ah, I missed #522. Looks good :)

**Comment by iGio90** [comment]
@jay8ee im waiting for some additional reports. Actually i tested it with more then 5 accts, but please, wanna hear something from others if it gives any kind of troubles

**Pull request closed without merging**
