### PR TITLE
Update Hash endpoint, version and UK25

### PR DESCRIPTION
**Pull request by Furtif**

### CODE REVIEW

**Comment by Gegy** [comment]
Could you update the protos too?

**Comment by Furtif** [comment]
Will try I'm not too gifted in java ^^

**Comment by Furtif** [comment]
Here is the submodule is updated

**Comment by Furtif** [comment]
Your ptr8 is located or need to update it too ??

**Comment by Gegy** [comment]
That's not updated yet

**Comment by Furtif** [comment]
Give me the link or is your ptr8 if you wanted

**Pull request merged**
