### PR TITLE
Issue 558

### PR DESCRIPTION
**Pull request by olegshulyakov**
**Fixed issue:** [https://github.com/Grover-c13/PokeGOAPI-Java/issues/558]

**Changes made:**
- removed lazy initialization of inventory
- migrated to concurrent collections in inventory package

### CODE REVIEW

**Comment by FabianTerhorst** [comment]
We had at the start a http request for a force load, but i think we decided to drop this, because of the http request on object creation.

**Comment by olegshulyakov** [comment]
I thought about using cache for inventory and update it like map objects

**Comment by AbandonedCart** [comment]
In my tests, this actually causes a warning (and login failure) where there wasn't one before

**Comment by FabianTerhorst** [comment]
I can login with this pull request, i can also catch a pokemon. Most of your changes are bad for the performance. Fro example: CopyOnWriteArraySet is slower then HashSet or ConcurrentMap is slower then HashMap.

**Comment by FabianTerhorst** [comment]
The most concurrent exceptions you can prevent by creating a new array or hashmap from the returned value instead of using the reference.

**Pull request closed without merging**
