### PR TITLE
Add throws when account appears to be banned

### PR DESCRIPTION
**Pull request by Grover-c13**
Add throws when account appears to be banned

### CODE REVIEW

**Comment by pvanassen** [comment]
Why not a BannedException or something of that kind so api users can catch it and handle it properly?

**Comment by Paul776** [comment]
+1...

**Comment by Grover-c13** [comment]
Because status code 3 is not exclusive for bans, for example sending a request with invalid fields will result in a 3. Ideally this wouldnt happen in the API but still can, and until that time we will keep it like this. Its also why the message says you may be banned

**Comment by FabianTerhorst** [comment]
Maybe we should just return the status codes in the exception messenges so that the applications can catch them and getMessage() == 3 //Maybe ban.

**Comment by AbandonedCart** [comment]
Even with a banned account, you can get a contents of buffer null exception before it has the chance to return this one. My opinion is to leave it to the user, since it sounds too unreliable.

**Comment by Paul776** [comment]
Leave to the use but how?  How do you check the account is banned?  You need to retrieve the cause and then the message and then compared it to see if it contains the word ban.  This totally unacceptable...

**Pull request merged**
