### PR TITLE
Development

### PR DESCRIPTION
**Pull request by gionata-bisciari**
*Fixed Pokemon.canEvolve():boolean, now checks if the pokemon reached the maximum evolution form;
+Added Pokemon.canPowerUp(considerMaxCPLimitForPlayerLevel:boolean):boolean so now passing true it checks if the pokemon already reached its current maximum cp for player level

### CODE REVIEW

**Comment by AbandonedCart** [comment]
It would probably be easier to rebase this instead of adding the existing commits and then having to patch them to fit the current state of the repository.

**Comment by AbandonedCart** [comment]
You can also clone https://github.com/AbandonedCart/PokeGOAPI-Java/tree/evolution and use that to submit the pull request if that will make it easier.

**Comment by gionata-bisciari** [comment]
I didn't know, sorry, and thanks

**Comment by AbandonedCart** [comment]
No need to apologize. It's just easier to look at that way and avoids a few extra commits. 
It wouldn't cause any real issues, though.

**Pull request closed without merging**
