### PR TITLE
improve PokemonGo instance naming

### PR DESCRIPTION
**Pull request by FabianTerhorst**

### CODE REVIEW

**Comment by AbandonedCart** [comment]
That fits with the more recent changes, but instance should probably still be instance to avoid confusion.

**Comment by FabianTerhorst** [comment]
On more then 90% of the files its named api so i thought this was a decision from someone.

**Comment by FabianTerhorst** [comment]
@Grover-c13 rename them all to instance or to api ?

**Comment by AbandonedCart** [comment]
Yeah, I just realized where that was located. I thought it was some sort of cached instance. Nevermind

**Comment by FabianTerhorst** [comment]
Its just the object reference.

**Comment by AbandonedCart** [comment]
Yeah. I was looking at the egg hatching and the excerpt looked like it was a different file. I was thinking a cached instance, like when an app makes a static instance that it keeps private. It was just another per-class reference with a different name, though.

**Pull request merged**
