### PR TITLE
0.79.3

### PR DESCRIPTION
**Pull request by Gegy**
Update to 0.79.3:
 - Replaces `GET_INVENTORY` request with `GET_HOLO_INVENTORY`
 - Adds (currently random) UK27 value to signature
 - Update hashing endpoint, UK25 and version number
 - Update PTC error handling

### CODE REVIEW

**Comment by Tommy-Emmanuel** [comment]
**BUILD FAILED WITH AN EXCEPTION**:

"FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':library'.
> No signature of method: org.gradle.api.internal.tasks.DefaultTaskInputs.source() is applicable for argument types: (com.google.protobuf.gradle.ProtobufSourceDirectorySet_Decorated) values: [main Proto source]
  Possible solutions: collect(), use([Ljava.lang.Object;)"

**Comment by Tommy-Emmanuel** [comment]
Hi @gegy1000 : You fixed proto submodule but still old bug.

"FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':library'.
> No signature of method: org.gradle.api.internal.tasks.DefaultTaskInputs.source() is applicable for argument types: (com.google.protobuf.gradle.ProtobufSourceDirectorySet_Decorated) values: [main Proto source]
  Possible solutions: collect(), use([Ljava.lang.Object;)"

**Comment by Gegy** [comment]
@Tommy-Emmanuel I can't reproduce this, and the Travis build is passing fine. What Gradle version are you using?

**Comment by Tommy-Emmanuel** [comment]
@gegy1000 : Gradle 4.2.1
------------------------------------------------------------

Build time:   2017-10-02 15:36:21 UTC
Revision:     a88ebd6be7840c2e59ae4782eb0f27fbe3405ddf

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          9.0.1 (Oracle Corporation 9.0.1+11)
OS:           Mac OS X 10.12 x86_64

**Comment by Gegy** [comment]
Try use the Gradle wrapper, it seems the protobuf plugin doesn't support Gradle 4.2.

**Comment by Tommy-Emmanuel** [comment]
It works! Thanks @gegy1000  👍

**Pull request merged**
