### PR TITLE
split project into modules

### PR DESCRIPTION
**Pull request by FabianTerhorst**

### CODE REVIEW

**Comment by FabianTerhorst** [comment]
@TwoStone a pr for the protos would be awesome.

**Comment by Grover-c13** [comment]
so tldr, splits the api and examples?

**Comment by FabianTerhorst** [comment]
yes and so its easier to add  maven upload script.

**Comment by Grover-c13** [comment]
can you fix for travis

**Comment by FabianTerhorst** [comment]
yes i have to init the sumodule

**Comment by FabianTerhorst** [comment]
when travis is rebuilding it should build correctly.

**Comment by FabianTerhorst** [comment]
Now checkstyle has to be fixed

**Comment by FabianTerhorst** [comment]
Checkstyle is working with 7 warnings from source files now

**Comment by FabianTerhorst** [comment]
:tada:

**Comment by FabianTerhorst** [comment]
next pr will be for maven upload i think.

**Comment by FabianTerhorst** [comment]
@Grover-c13 review and merge please

**Comment by jabbink** [comment]
```
[ant:checkstyle] [WARN] /home/jasper/Documents/PokemonGo/PokeGOAPI-Java/library/src/main/java/com/pokegoapi/api/map/Map.java:380: 'method def' child have incorrect indentation level 8, expected level should be one of the following: 12, 14, 16. [Indentation]
[ant:checkstyle] [WARN] /home/jasper/Documents/PokemonGo/PokeGOAPI-Java/library/src/main/java/com/pokegoapi/api/map/Map.java:381: 'method def rcurly' have incorrect indentation level 6, expected level should be one of the following: 10, 12, 14. [Indentation]
[ant:checkstyle] [WARN] /home/jasper/Documents/PokemonGo/PokeGOAPI-Java/library/src/main/java/com/pokegoapi/api/map/Map.java:382: 'object def rcurly' have incorrect indentation level 4, expected level should be one of the following: 8, 10, 12. [Indentation]
[ant:checkstyle] [WARN] /home/jasper/Documents/PokemonGo/PokeGOAPI-Java/library/src/main/java/com/pokegoapi/api/map/fort/Pokestop.java:130: Line is longer than 120 characters (found 123). [LineLength]
[ant:checkstyle] [WARN] /home/jasper/Documents/PokemonGo/PokeGOAPI-Java/library/src/main/java/com/pokegoapi/api/map/pokemon/CatchablePokemon.java:397: Line is longer than 120 characters (found 123). [LineLength]
[ant:checkstyle] [WARN] /home/jasper/Documents/PokemonGo/PokeGOAPI-Java/library/src/main/java/com/pokegoapi/api/map/pokemon/CatchablePokemon.java:435: Indent must use tab characters [RegexpSinglelineJava]
[ant:checkstyle] [WARN] /home/jasper/Documents/PokemonGo/PokeGOAPI-Java/library/src/main/java/com/pokegoapi/util/AsyncHelper.java:15: 'package' should be separated from previous statement. [EmptyLineSeparator]
!!!!-----------------------------------!!!!
There were checkstyle warnings! For more info check /home/jasper/Documents/PokemonGo/PokeGOAPI-Java/library/build/reports/checkstyle/main.xml
PLEASE CORRECT BEFORE SUBMITTING A PULLREQUEST
!!!!-----------------------------------!!!!
```

Those are fixed in #426 

Will manually merge these two PR's and run my huge integration test for 30 mins (aka run my bot) and see if everything works. God, I love the testing options this project utilizes :joy:

**Comment by FabianTerhorst** [comment]
thanks

**Comment by jabbink** [comment]
Including this library in another project just became kind of impossible. When you include the root project, all deps of the library are inaccessible, if you directly include the `library` module, the gradle protoc compiler is inaccessible (as it's defined in the root project, which wouldn't even need it afaik)

**Comment by FabianTerhorst** [comment]
@jabbink its the default setup for a multi module project. The plugins are defined in the root build gradle. You´ll never include it directly into another project. You use the jar or the maven repository.

**Comment by FabianTerhorst** [comment]
Thats the reason why the next think should be a maven publish script.

**Comment by jabbink** [comment]
> its the default setup for a multi module project.

Correct, but most multi module projects specify the deps in such a way that building a single module that doesn't depend on a different one will work (eg build library without samples). As the deps and repos it gets its files from are now defined in the rootmodule (also the protoc dep is there; for the rest only the repos?!) this is no longer possible.

> You´ll never include it directly into another project.

There are always reasons why you would want to do that, and also works fine with Gradle, when the deps are set up correctly.

Also jitpack randomly fails to actually publish data or give the entire globe access to the jars, so they are **not** an option for me.

**Comment by FabianTerhorst** [comment]
check latest commit

**Comment by FabianTerhorst** [comment]
The problem is that the sample can´t resolve the dependencies when the library got bundled as a jar with dependencies. Without the bundle task the sample can be build.

**Comment by FabianTerhorst** [comment]
The build is generating two jars now. This is fixing the sample build, but also allows users to use the jar without dependencies. So there can add them with gradle.

**Comment by jabbink** [comment]
Yeah, seems better now. Will test

**Comment by AbandonedCart** [comment]
It may be beneficial if it's part of PRs to clean it all up, start a fresh clone, and then reapply the changes to submit a final pull for merge. It would be much cleaner than a bunch of steps that add, remove, and re-add something and wouldn't lead to a merge nightmare. 

Just my opinion, but doing it like this is a lot of extra hassle, especially if something were to go wrong and you had to locate the one commit of 10 in the change that caused it.

Edit: The commits from PR #426 are dropped when doing a fetch / rebase or performing a hard reset.

**Comment by jabbink** [comment]
Unfortunately @Grover-c13 removed the ability to squash commits directly from the GH UI, so apparently he doesn't like losing part of the history.

**Comment by AbandonedCart** [comment]
@jabbink It isn't done from the site. The person submitting the pull would checkout a new branch, reapply the necessary changes, and close the pull in favor of a new one.

It is also possible to `git rebase -i HEAD~(number of commits)`, squash a few that are trial and error, then `git push -f` to overwrite the existing string of commits. Again, it is the PR author that is responsible for cleaning it up, though. Keep in mind, no history is lost. Commits are simply merged.

**Pull request merged**
