### PR TITLE
add deployPokemon method

### PR DESCRIPTION
**Pull request by michibat01**

### CODE REVIEW

**Comment by FabianTerhorst** [comment]
Can you add a async method as well with rxjava?

**Comment by AbandonedCart** [comment]
```
[ant:checkstyle] [WARN] PokeGOAPI-Java/library/src/main/java/com/pokegoapi/api/gym/Gym.java:185: Line is longer than 120 characters (found 125). [LineLength]
[ant:checkstyle] [WARN] PokeGOAPI-Java/library/src/main/java/com/pokegoapi/api/gym/Gym.java:216: Line is longer than 120 characters (found 142). [LineLength]
[ant:checkstyle] [WARN] PokeGOAPI-Java/library/src/main/java/com/pokegoapi/api/gym/Gym.java:226: Line is longer than 120 characters (found 142). [LineLength]
!!!!-----------------------------------!!!!
There were checkstyle warnings!
PLEASE CORRECT BEFORE SUBMITTING A PULLREQUEST
!!!!-----------------------------------!!!!
```

**Comment by FabianTerhorst** [comment]
Signature 85 will be fixed in #650. The pr for the save implementation to support android had this issue.

**Comment by LoungeKatt** [comment]
@FabianTerhorst It is a paste of the output. There is really no need to critique it.

**Comment by FabianTerhorst** [comment]
Can you check your ide spacings? Switch them to taps please.

**Comment by AbandonedCart** [comment]
It might be easier to revert the last commit then just go back and split lines 185, 216, and 226

**Comment by michibat01** [comment]
Sorry for mistake

**Pull request closed without merging**
