### PR TITLE
clear cache when location is changed

### LINKED ISSUE #646: getCatchablePokemon() and getWildPokemon() unexpected behavior
**Description:**
When I call getCatchablePokemon() and getWildPokemon() at a certain coordinate, say (40.781549,-73.9650843646)
I get a set of pokemon, which is expected. However, when I make another right after on a point a couple of hundred meters away (40.781549,-73.9638913646) I get the exact same set of pokemon for the second point as well. 
When I only call the second point by itself I get an empty set of pokemon or a different set.
The problem occurs when I call two or more points in succession. 

**Steps to reproduce:**
1. [Step 1] Call getWildPokemon() at point A 
2. [Step 2] Call getWildPokemon() at point B (Note that i get the same set as in point A)
3. [Step 3] Call getWildPokemon() at point B (Get empty set or different pokemon)

**Expected behavior:**
I should be getting a different set of pokemon per point, provided that the points don't over lap.

**Actual behavior:**
I get the same set of pokemon for both points, but different sets if called separetly. 

**Version:**
Version 0.4.0

### PR DESCRIPTION
**Pull request by FabianTerhorst**
fix #646

### CODE REVIEW

**Comment by FabianTerhorst** [comment]
style warnings are fixed in #650

**Comment by xae217** [comment]
Hey I just included this commit to my build but I'm gettinf a null pointer exception.

```
Exception in thread "Thread-0" java.lang.NullPointerException
    at com.pokegoapi.api.map.Map.clearCache(Map.java:697)
    at com.pokegoapi.api.PokemonGo.setLocation(PokemonGo.java:138)
    at poketest.PokeScanner.scan(PokeScanner.java:257)
    at poketest.PokeScanner.patrol(PokeScanner.java:331)
    at poketest.PokeScanner.run(PokeScanner.java:211)
    at java.lang.Thread.run(Thread.java:745)
```

Any ideas? For some reason cachedCatchable is null.

**Comment by FabianTerhorst** [comment]
I will check for null then. I also don´t know when there are null.

**Comment by FabianTerhorst** [comment]
there are setted to null instead of getting cleared

**Comment by FabianTerhorst** [comment]
when the cache isn´t needed.

**Comment by FabianTerhorst** [comment]
maybe we could clear the list instead of setting it null

**Comment by FabianTerhorst** [comment]
@xae217 you can retest

**Comment by xae217** [comment]
@FabianTerhorst It works now and seems to have fixed #646.

**Pull request merged**
