### PR TITLE
Modified Pokemon.java

### PR DESCRIPTION
**Pull request by gionata-bisciari**
- Fixed Pokemon.canEvolve():boolean, now checks if the pokemon reached the maximum evolution form;
- Added Pokemon.canPowerUp(considerMaxCPLimitForPlayerLevel:boolean):boolean so now passing true it checks if the pokemon already reached its current maximum cp for player level

### CODE REVIEW

**Comment by AbandonedCart** [comment]
@FabianTerhorst This PR was closed 2 hours ago...

**Comment by FabianTerhorst** [comment]
But he will create another pr with the same changes

**Comment by FabianTerhorst** [comment]
So he can fix them before publishing the pr.

**Comment by AbandonedCart** [comment]
See https://github.com/Grover-c13/PokeGOAPI-Java/pull/624. He was already notified about it.
You also made identical comments on https://github.com/Grover-c13/PokeGOAPI-Java/pull/623, which is redundant.

**Comment by FabianTerhorst** [comment]
This is the same commit thats because github is showing the comments on both.

**Comment by gionata-bisciari** [comment]
sorry but I made lots of mistakes... I hope the new pull is ok...

**Pull request closed without merging**
