### PR TITLE
Fixed Translation FR

### PR DESCRIPTION
**Pull request by iSach**
The translation system was making issues with accents and symbols like œ in French.
This fixes it.

### CODE REVIEW

**Comment by iSach** [comment]
http://hastebin.com/igiladazug.vbs

**Comment by Cyperghost** [comment]
Remove the .DS_Store :)

**Comment by FabianTerhorst** [comment]
You may be used the wrong tabcount to reindent the file?

**Comment by iSach** [comment]
I'm fixing this ^^

**Pull request closed without merging**
